title: Fanish Shukla
tagline: Enterprise Architect | Cloud & Technology Strategy
url: "https://fanish.shukla.eu"
author: Fanish Shukla

theme: jekyll-theme-chirpy

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-archives
  - jekyll-include-cache
