title: Fanish Shukla
tagline: Enterprise Architect | Cloud & Technology Strategy
url: "https://fanish.shukla.eu"
author: Fanish Shukla
description: "Enterprise Architecture, Cloud Strategy, and Aviation Systems."

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
# Enable excerpt parsing for feeds
excerpt_separator: "\n\n"
